spring:
  application:
    name: Keeper
  redis:
    enableCluster: false
    password: lanredis
    connectionTimeout: 29999
    cluster:
      nodeAddresses: [
        "redis://127.0.0.1:7005",
        "redis://127.0.0.1:7004",
        "redis://127.0.0.1:7003",
        "redis://127.0.0.1:7002",
        "redis://127.0.0.1:7001",
        "redis://127.0.0.1:7000"
      ]
    single:
      address: "redis://127.0.0.1:6379"
      database: 7

amqp:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 9988
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


project:
  server-config:
    # WebSocket Path
    contextPath: /ws
    # 服务绑定的端口号
    serverPort: 9966
    # HttpObjectAggregator MaxContentLength
    httpObjectLength:
    # TCP 全队列大小
    soBacklog: 2048
  plugin-config:
    # 开启心跳
    enableHearBeat: false
    # 设置心跳周期，单位 S
    hearBeatCycle: 15
