spring:
  application:
    name: Keeper
  redis:
    host: 192.168.83.22
    port: 6379
    password:
    database: 11
    lettuce:
      pool:
        max-active: 16
        max-wait: 3000ms
        max-idle: 16
        min-idle: 0

amqp:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 9988
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


project:
  server-config:
    # WebSocket Path
    contextPath: /ws
    # 服务绑定的端口号
    serverPort: 9966
    # HttpObjectAggregator MaxContentLength
    httpObjectLength:
    # TCP 全队列大小
    soBacklog: 2048
  plugin-config:
    # 开启心跳
    enableHearBeat: false
    # 设置心跳周期，单位 S
    hearBeatCycle: 15
    # 开启事件循环
    enableEventLoop: false
    # 设置事件循环周期，单位 S
    eventLoopCycle: 15
